# Generated by Django 3.0.4 on 2020-05-03 07:24

import datetime
from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0012_transactions'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetBanking',
            fields=[
                ('Username', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('Password', models.CharField(max_length=14)),
                ('Bank', models.CharField(max_length=25)),
                ('Balance', models.CharField(max_length=9)),
            ],
        ),
        migrations.AlterField(
            model_name='cards',
            name='email',
            field=models.EmailField(default='rambarodavala21@gmail.com', max_length=50),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='Date_Time',
            field=models.DateTimeField(default=timezone.now),
        ),
    ]
