# Generated by Django 3.0.4 on 2020-05-16 04:09

import datetime
from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0013_auto_20200503_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessanger_detail',
            name='pay_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='Date_Time',
            field=models.DateTimeField(default=timezone.now),
        ),
    ]
