# Generated by Django 5.0.2 on 2024-03-06 07:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0015_auto_20200516_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='Date_Time',
            field=models.CharField(default=datetime.datetime(2024, 3, 6, 7, 44, 20, 584889, tzinfo=datetime.timezone.utc), max_length=19),
        ),
    ]
